<a href="https://colab.research.google.com/github/practigol/trabajo_final/blob/main/crear_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
%matplotlib inline

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
import warnings

warnings.filterwarnings('ignore')

In [2]:
from google.colab import files
uploaded  = files.upload()

Saving usu_individual_T421.csv to usu_individual_T421.csv

In [3]:
df_individual = pd.read_csv("usu_individual_T421.csv")

In [ ]:
df_individual.shape

(50154, 177)

In [4]:
condiciones = [
    (df_individual ['CH04'] >= 1) & (df_individual['CH06'] < 1),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 1),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 2),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 3),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 4),
    (df_individual['CH04'] >= 1 ) & ( df_individual['CH06'] == 5),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 6),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 7),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 8),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 9),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 10),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 11),
    (df_individual['CH04'] >= 1) & (df_individual['CH06'] == 12),
    (df_individual['CH04'] == 2) & (df_individual['CH06'] >= 13) & (df_individual['CH06'] <=14),
    (df_individual['CH04'] == 2) & (df_individual['CH06'] >= 15) & (df_individual['CH06'] <=17),
    (df_individual['CH04'] == 2) & (df_individual['CH06'] >= 18) & (df_individual['CH06'] <=29),
    (df_individual['CH04'] == 2) & (df_individual['CH06'] >= 30) & (df_individual['CH06'] <=45),
    (df_individual['CH04'] == 2) & (df_individual['CH06'] >= 46) & (df_individual['CH06'] <=60),
    (df_individual['CH04'] == 2) & (df_individual['CH06'] >= 61) & (df_individual['CH06'] <=75),
    (df_individual['CH04'] == 2) & (df_individual['CH06'] > 75),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] ==10),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] ==11),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] ==12),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] ==13),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] ==14),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] ==15),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] ==16),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] ==17),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] >= 18) & (df_individual['CH06'] <=29),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] >= 30) & (df_individual['CH06'] <=45),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] >= 46) & (df_individual['CH06'] <=60),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] >= 61) & (df_individual['CH06'] <=75),
    (df_individual['CH04'] == 1) & (df_individual['CH06'] > 75)   
    ]

opciones = [0.35,0.37,0.46,0.51,0.55,0.60,0.64,0.66,0.68,0.69,0.70,0.72,0.74,0.76,0.77,0.76,0.77,0.76,0.67,0.63,0.79,0.82,0.85,0.90,
            0.96,1.00,1.03,1.04,1.02,1.00,1.00,0.83,0.74]

In [5]:
df_individual['AE_ctrol_ind']=np.select(condiciones,opciones)

In [6]:
df_individual.head()

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,ADECIFR,IPCF,DECCFR,IDECCFR,RDECCFR,GDECCFR,PDECCFR,ADECCFR,PONDIH,AE_ctrol_ind
0,TQRMNOPPQHMOLPCDEGNFJ00714305,2021,4,1,4,1,44,N,17,309,...,7,33500.0,6,7.0,5,NaN,7.0,5,411,0.90
1,TQRMNOQPYHKMPUCDEIJAH00663642,2021,4,1,1,1,1,S,33,1573,...,4,32000.0,6,NaN,6,6.0,NaN,6,2285,0.74
2,TQRMNOQPYHKMPUCDEIJAH00663642,2021,4,1,2,1,1,S,33,1573,...,4,32000.0,6,NaN,6,6.0,NaN,6,2285,0.63
3,TQRMNOQYRHMOQRCDEIJAH00718661,2021,4,1,1,1,1,S,33,2635,...,12,0.0,12,NaN,12,12.0,NaN,12,0,1.00
4,TQRMNOPSTHMMLPCDEFMDB00713515,2021,4,1,2,1,43,N,6,87,...,7,43000.0,7,8.0,8,NaN,8.0,8,129,0.67

In [10]:
df_personas = df_individual[['CODUSU','CH03','CH04','CH06','CH08','NIVEL_ED','CAT_OCUP','CAT_INAC','CH11','AE_ctrol_ind']]

In [11]:
df_personas.head()

,CODUSU,CH03,CH04,CH06,CH08,NIVEL_ED,CAT_OCUP,CAT_INAC,CH11,AE_ctrol_ind
0,TQRMNOPPQHMOLPCDEGNFJ00714305,3,1,13,1,3,0,3,1,0.90
1,TQRMNOQPYHKMPUCDEIJAH00663642,1,1,79,1,2,0,1,0,0.74
2,TQRMNOQPYHKMPUCDEIJAH00663642,2,2,79,1,3,0,1,0,0.63
3,TQRMNOQYRHMOQRCDEIJAH00718661,1,1,48,1,4,3,0,0,1.00
4,TQRMNOPSTHMMLPCDEFMDB00713515,2,2,65,1,4,0,1,0,0.67

In [12]:
df_personas.to_csv('personas.csv')

In [14]:
df_suma = df_personas.groupby("CODUSU").AE_ctrol_ind.sum()

In [16]:
df_personas.head()

CODUSU
TQRMNOPPQHJLKTCDEGNFJ00699079    1.40
TQRMNOPPQHJMKMCDEFKID00667054    1.77
TQRMNOPPQHJMKMCDEOJAH00697751    0.63
TQRMNOPPQHJMKTCDEHNHB00686535    2.19
TQRMNOPPQHJMLPCDEFNFF00670213    1.52
Name: AE_ctrol_ind, dtype: float64

In [17]:
df_suma.shape

(16898,)

In [20]:
df_personas_suma = pd.merge(df_personas, df_suma, on='CODUSU')

In [22]:
df_personas_suma.head(20)

,CODUSU,CH03,CH04,CH06,CH08,NIVEL_ED,CAT_OCUP,CAT_INAC,CH11,AE_ctrol_ind_x,AE_ctrol_ind_y
0,TQRMNOPPQHMOLPCDEGNFJ00714305,3,1,13,1,3,0,3,1,0.90,3.35
1,TQRMNOPPQHMOLPCDEGNFJ00714305,1,2,37,1,6,3,0,0,0.77,3.35
2,TQRMNOPPQHMOLPCDEGNFJ00714305,2,1,37,1,4,3,0,0,1.00,3.35
3,TQRMNOPPQHMOLPCDEGNFJ00714305,3,2,8,1,1,0,3,1,0.68,3.35
4,TQRMNOQPYHKMPUCDEIJAH00663642,1,1,79,1,2,0,1,0,0.74,1.37
5,TQRMNOQPYHKMPUCDEIJAH00663642,2,2,79,1,3,0,1,0,0.63,1.37
6,TQRMNOQYRHMOQRCDEIJAH00718661,1,1,48,1,4,3,0,0,1.00,4.24
7,TQRMNOQYRHMOQRCDEIJAH00718661,2,2,48,1,2,0,4,0,0.76,4.24
8,TQRMNOQYRHMOQRCDEIJAH00718661,3,2,25,1,4,0,4,0,0.76,4.24
9,TQRMNOQYRHMOQRCDEIJAH00718661,4,1,23,1,2,3,0,0,1.02,4.24
10,TQRMNOQYRHMOQRCDEIJAH00718661,5,1,10,1,1,0,1,2,0.70,4.24
11,TQRMNOPSTHMMLPCDEFMDB00713515,2,2,65,1,4,0,1,0,0.67,1.50
12,TQRMNOPSTHMMLPCDEFMDB00713515,1,1,67,1,5,0,1,0,0.83,1.50
13,TQRMNOQQSHJMKUCDEHJGH00702130,1,2,76,1,6,0,1,0,0.63,1.63
14,TQRMNOQQSHJMKUCDEHJGH00702130,3,1,45,12,6,3,0,0,1.00,1.63
15,TQRMNOPPRHJLKTCDEGNFJ00678218,1,2,61,1,4,0,1,0,0.67,3.75
16,TQRMNOPPRHJLKTCDEGNFJ00678218,3,2,29,1,4,3,0,0,0.76,3.75
17,TQRMNOPPRHJLKTCDEGNFJ00678218,5,1,8,1,1,0,3,1,0.68,3.75
18,TQRMNOPPRHJLKTCDEGNFJ00678218,5,2,6,1,1,0,3,1,0.64,3.75
19,TQRMNOPPRHJLKTCDEGNFJ00678218,4,1,32,1,4,3,0,0,1.00,3.75

In [25]:
df_personas_suma.to_csv('personas_suma.csv')